name: money_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: ^3.5.3

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  flutter_staggered_grid_view: ^0.7.0
  glassmorphism: ^3.0.0
  flutter_neumorphic_plus: ^3.4.0
  chips_choice: ^3.0.1
  intl: ^0.19.0
  lottie: ^3.1.3

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

